# Generated by Django 5.2.4 on 2025-07-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactions',
            name='waveform_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
